"""Etsy listing packager for Archive-35.

Generates formatted listing packages from content:
title, 13 tags, description, price, category.
Saves as markdown files ready for paste into Etsy.
"""

from __future__ import annotations

import json
import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.brand.sku import calculate_min_price, get_base_cost

logger = logging.getLogger(__name__)

ETSY_TAG_LIMIT = 13
ETSY_TITLE_MAX_LENGTH = 140

# Default category for fine art prints
DEFAULT_CATEGORY = "Art & Collectibles > Photography > Color"

LISTING_TEMPLATE = """# Etsy Listing: {title}

**Generated:** {generated_at}
**SKU:** {sku}
**Price:** ${price:.2f}
**Category:** {category}

## Title
{title}

## Description
{description}

## Tags ({tag_count}/13)
{tags}

## Pricing Breakdown
- Base cost: ${base_cost:.2f}
- Min floor: ${min_price:.2f}
- List price: ${price:.2f}
- Estimated margin: {margin_pct:.0f}%

## Provenance
{provenance}

---
*Auto-generated by Archive-35 Agent*
"""


def _ensure_13_tags(tags: list[str]) -> list[str]:
    """Ensure exactly 13 tags for Etsy (pad or trim)."""
    # Clean and dedupe
    cleaned = []
    seen = set()
    for tag in tags:
        t = tag.strip().lower().replace("#", "")
        if t and t not in seen and len(t) <= 20:
            cleaned.append(t)
            seen.add(t)

    # Pad with generic tags if needed
    padding_tags = [
        "fine art print", "wall art", "photography print",
        "home decor", "art photography", "travel photography",
        "gallery wall", "modern art", "minimal art",
        "nature photography", "landscape print", "limited edition",
        "gift for art lover",
    ]

    while len(cleaned) < ETSY_TAG_LIMIT:
        for pt in padding_tags:
            if pt not in seen:
                cleaned.append(pt)
                seen.add(pt)
                if len(cleaned) >= ETSY_TAG_LIMIT:
                    break

    return cleaned[:ETSY_TAG_LIMIT]


def _format_title(body: str, collection: Optional[str] = None) -> str:
    """Create an Etsy-optimized title from content body."""
    # Take first sentence or first 100 chars
    title = body.split(".")[0].strip()
    if len(title) > ETSY_TITLE_MAX_LENGTH:
        title = title[:ETSY_TITLE_MAX_LENGTH - 3] + "..."

    # Add collection tag if available
    if collection and collection.upper() not in title.upper():
        suffix = f" | {collection} Collection"
        if len(title) + len(suffix) <= ETSY_TITLE_MAX_LENGTH:
            title += suffix

    return title


def generate_listing(
    conn: sqlite3.Connection,
    content_id: str,
    size_code: str = "16R",
    paper_code: str = "HAH",
    sku: Optional[str] = None,
    output_dir: Optional[str | Path] = None,
) -> Optional[dict]:
    """Generate an Etsy listing package from content.

    Args:
        conn: Active database connection.
        content_id: Content ID (should be an etsy-type content).
        size_code: Default print size.
        paper_code: Default paper type.
        sku: Optional pre-generated SKU.
        output_dir: Directory to save listing markdown.

    Returns:
        Dict with listing details, or None if failed.
    """
    # Fetch content
    content = conn.execute(
        "SELECT * FROM content WHERE id = ?",
        (content_id,),
    ).fetchone()

    if not content:
        logger.error("Content %s not found", content_id)
        return None

    # Fetch photo for collection info
    photo = conn.execute(
        "SELECT * FROM photos WHERE id = ?",
        (content["photo_id"],),
    ).fetchone()

    collection = photo["collection"] if photo else None

    # Build listing
    body = content["body"]
    raw_tags = json.loads(content["tags"]) if content["tags"] else []
    tags = _ensure_13_tags(raw_tags)
    title = _format_title(body, collection)

    # Pricing
    base_cost = get_base_cost(size_code, paper_code)
    if base_cost == 0:
        base_cost = 25.0
    min_price = calculate_min_price(base_cost, size_code)
    list_price = round(min_price * 1.2, 2)

    # Margin calculation
    margin_pct = ((list_price - base_cost) / list_price) * 100 if list_price > 0 else 0

    listing = {
        "title": title,
        "description": body,
        "tags": tags,
        "tag_count": len(tags),
        "price": list_price,
        "base_cost": base_cost,
        "min_price": min_price,
        "margin_pct": margin_pct,
        "category": DEFAULT_CATEGORY,
        "sku": sku or "TBD",
        "provenance": content["provenance"] or "Part of The Restless Eye collection.",
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

    # Save to file if output_dir provided
    if output_dir:
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        filename = f"listing_{content_id[:8]}.md"
        filepath = out_path / filename

        md_content = LISTING_TEMPLATE.format(**listing)
        filepath.write_text(md_content)
        listing["file_path"] = str(filepath)
        logger.info("Saved listing to %s", filepath)

    return listing
